### ISSUE TITLE
using GAFF:  ValueError: Found multiple definitions for atom type: c 

### ISSUE THREAD

**Issue by SchroedingersLion** [openmm/openmmforcefields#303]
Greetings, 

I am new to OpenMM, so apologies in advance for a possibly trivial question.
Any help would be appreciated!

I try to use GAFF to simulate Butane from a PDB file, and I am getting the error in the title.

My code:
```python
from openmm.app import *
from openmm import *
from openmm.unit import *

#%% prepare force field for small molecule Butane
# Create an OpenFF Molecule object for benzene from SMILES
from openff.toolkit.topology import Molecule
molecule = Molecule.from_smiles('CCCC')

# Create the GAFF template generator
from openmmforcefields.generators import GAFFTemplateGenerator
gaff = GAFFTemplateGenerator(molecules=molecule)

# Create an OpenMM ForceField object with AMBER ff14SB and TIP3P with compatible ions
from openmm.app import ForceField
forcefield = ForceField('/openmmforcefields/ffxml/amber/gaff/ffxml/gaff.xml', 
                        'amber14/tip3p.xml')

# Register the GAFF template generator
forcefield.registerTemplateGenerator(gaff.generator)

#%% create system
file = "butane.pdb"
pdb = PDBFile(file)

## need to add water molecules
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(forcefield, padding=1.0*nanometers)

system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME)  # the error is thrown

simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)

```

Full error message:
```

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/Butane/butane_simu.py", line 60, in <module>
    system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME)

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1212, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1417, in _matchAllResiduesToTemplates
    if generator(self, res):

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmmforcefields/generators/template_generators.py", line 537, in generator
    forcefield.loadFile(self.gaff_xml_filename)

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmm/app/forcefield.py", line 288, in loadFile
    self.registerAtomType(type.attrib)

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmm/app/forcefield.py", line 433, in registerAtomType
    raise ValueError('Found multiple definitions for atom type: '+name)

ValueError: Found multiple definitions for atom type: c
```

The PDB file:
```
REMARK  TITLE                                                                         
REMARK  CREATED BY NAME                       
REMARK  AT 2016/04/18 03:41:02                                                        
REMARK   DATE:    12/19/19     21:19:35      CREATED BY USER: name                 
ATOM      1  H11 BUTA    1       0.353  -0.822   0.042  1.00  0.00      SEG 
ATOM      2  H12 BUTA    1       1.572   0.403   0.559  1.00  0.00      SEG 
ATOM      3  H13 BUTA    1       0.240   0.873  -0.561  1.00  0.00      SEG 
ATOM      4  C1  BUTA    1       0.945   0.058  -0.291  1.00  0.00      SEG 
ATOM      5  H21 BUTA    1       2.405   0.588  -1.804  1.00  0.00      SEG 
ATOM      6  H22 BUTA    1       2.553  -1.093  -1.191  1.00  0.00      SEG 
ATOM      7  C2  BUTA    1       1.821  -0.308  -1.493  1.00  0.00      SEG 
ATOM      8  H31 BUTA    1       0.243  -0.064  -2.956  1.00  0.00      SEG 
ATOM      9  H32 BUTA    1       0.493  -1.755  -2.406  1.00  0.00      SEG 
ATOM     10  C3  BUTA    1       1.021  -0.818  -2.698  1.00  0.00      SEG 
ATOM     11  H41 BUTA    1       2.385  -0.153  -4.267  1.00  0.00      SEG 
ATOM     12  H42 BUTA    1       2.670  -1.840  -3.702  1.00  0.00      SEG 
ATOM     13  H43 BUTA    1       1.264  -1.472  -4.769  1.00  0.00      SEG 
ATOM     14  C4  BUTA    1       1.886  -1.088  -3.932  1.00  0.00      SEG 
TER      15      BUTA     1
END
```

**Comment by jchodera** [comment]
Thanks for the clear bug report!

If you're using the `GAFFTemplateGenerator`, you should not need to specify `gaff.xml` to `ForceField`, since it already includes `gaff.xml` for you.

Can you try changing 
```python
forcefield = ForceField('/openmmforcefields/ffxml/amber/gaff/ffxml/gaff.xml', 
                        'amber14/tip3p.xml')
```
to
```python
forcefield = ForceField('amber14/tip3p.xml')
```
 and see if this works for you?

**Comment by SchroedingersLion** [comment]
> Thanks for the clear bug report!
> 
> If you're using the `GAFFTemplateGenerator`, you should not need to specify `gaff.xml` to `ForceField`, since it already includes `gaff.xml` for you.
> 
> Can you try changing
> 
> ```python
> forcefield = ForceField('/openmmforcefields/ffxml/amber/gaff/ffxml/gaff.xml', 
>                         'amber14/tip3p.xml')
> ```
> 
> to
> 
> ```python
> forcefield = ForceField('amber14/tip3p.xml')
> ```
> 
> and see if this works for you?

Thank you for the quick response.
After this change, I get the error
```python
Did not recognize residue BUTA; did you forget to call .add_molecules() to add it?
Traceback (most recent call last):

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/Butane/butane_simu.py", line 57, in <module>
    modeller.addSolvent(forcefield, padding=1.0*nanometers)

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmm/app/modeller.py", line 483, in addSolvent
    system = forcefield.createSystem(self.topology)

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1212, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)

  File "/home/anaconda3/envs/openmm2/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1427, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))

ValueError: No template found for residue 1 (BUTA).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```

**Comment by jchodera** [comment]
Apologies for missing this earlier! If you're loading your molecule structure in via a PDB file, the PDB reader assumes your file conforms to the [PDB File Specification](https://www.wwpdb.org/documentation/file-format), which requires `CONECT` records to describe bonds between your atoms if it's not one of the standard amino or nucleic acids. 

How did you generate your PDB file?

**Comment by SchroedingersLion** [comment]
It was provided to me by a third party whom I collaborate with. They are using it in their own modelling framework, and I want to use OpenMM to benchmark some of their results.

I am a complete beginner with .pdb files as well, but for a simple molecule such as Butane, manually adding these `CONECT` entries should be straightforward I would presume.

Does this format look correct? 
```
REMARK  TITLE                                                                         
REMARK  CREATED BY NAME                       
REMARK  AT 2016/04/18 03:41:02                                                        
REMARK   DATE:    12/19/19     21:19:35      CREATED BY USER: name                 
ATOM      1  H11 BUTA    1       0.353  -0.822   0.042  1.00  0.00      SEG 
ATOM      2  H12 BUTA    1       1.572   0.403   0.559  1.00  0.00      SEG 
ATOM      3  H13 BUTA    1       0.240   0.873  -0.561  1.00  0.00      SEG 
ATOM      4  C1  BUTA    1       0.945   0.058  -0.291  1.00  0.00      SEG 
ATOM      5  H21 BUTA    1       2.405   0.588  -1.804  1.00  0.00      SEG 
ATOM      6  H22 BUTA    1       2.553  -1.093  -1.191  1.00  0.00      SEG 
ATOM      7  C2  BUTA    1       1.821  -0.308  -1.493  1.00  0.00      SEG 
ATOM      8  H31 BUTA    1       0.243  -0.064  -2.956  1.00  0.00      SEG 
ATOM      9  H32 BUTA    1       0.493  -1.755  -2.406  1.00  0.00      SEG 
ATOM     10  C3  BUTA    1       1.021  -0.818  -2.698  1.00  0.00      SEG 
ATOM     11  H41 BUTA    1       2.385  -0.153  -4.267  1.00  0.00      SEG 
ATOM     12  H42 BUTA    1       2.670  -1.840  -3.702  1.00  0.00      SEG 
ATOM     13  H43 BUTA    1       1.264  -1.472  -4.769  1.00  0.00      SEG 
ATOM     14  C4  BUTA    1       1.886  -1.088  -3.932  1.00  0.00      SEG 

CONECT    4  1  2  3  7
CONECT    7  5  6  10 
CONECT    10 8  9  14
CONECT    14 11 12 13

TER      15      BUTA     1
END
```

**Comment by jchodera** [comment]
That *looks* correct to me. Let us know if it fails as well.

If the precise conformation isn't important, there's also a way to generate conformations from the SMILES string if you're using the OpenFF Toolkit.

**Comment by SchroedingersLion** [comment]
I still get the same error
`ValueError: No template found for residue 1 (BUTA).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.`

My goal is actually to load small molecules like this and test Langevin-like sampling schemes on them. I don't necessarily need to start in a certain configuration. Is your suggestion more appropriate for this?
`If the precise conformation isn't important, there's also a way to generate conformations from the SMILES string if you're using the OpenFF Toolkit.`

**Comment by mattwthompson** [comment]
There are a handful of ways to make a (OpenFF Toolkit) `Molecule` object - PDB files are just one way, and might not be the best for loading up small molecules depending on your data source. This documentation might be helpful starting point: https://docs.openforcefield.org/projects/toolkit/en/stable/users/molecule_cookbook.html

**Comment by mattwthompson** [comment]
Make sure you're using version 0.11.0 or newer

**Comment by jchodera** [comment]
@SchroedingersLion : Apologies for the frustrations you've had here. Can you give this gist a try?
https://gist.github.com/jchodera/8deaa644584b6cb7ec7cf4efdd720089

**Comment by SchroedingersLion** [comment]
> Make sure you're using version 0.11.0 or newer for that import path, otherwise point the documentation to the version you have installed

I had 0.10.0. After an upgrade I can import `Topology` successfully.

@jchodera Thank you so much, it works perfectly!

**Comment by SchroedingersLion** [comment]
Apologies @jchodera: When you said 

> If the precise conformation isn't important, there's also a way to generate conformations from the SMILES string if you're using 

> the OpenFF Toolkit.

I assumed you were referring to the starting position only. I do need the molecule to be flexible as I want to observe the dihedral angle as in [.](http://ursula.chem.yale.edu/~chem220/chem220js/STUDYAIDS/movies/butane.html). I am not sure whether the SMILES model is flexible enough?

How can I know how flexible the molecule is, i.e. what exactly the constraints are?
From printing out the PDB of the `system`, I count 243 water molecules. With 3 constraints per water molecule, that makes 729 constraints for the water. `simulation.context.getSystem().getNumConstraints()`, however, gives 739 constraints, which should imply that the Butane is treated with 10 constraints, which means that it should be somewhat flexible.

**Comment by jchodera** [comment]
@SchroedingersLion : The example I provided in the [gist](https://gist.github.com/jchodera/8deaa644584b6cb7ec7cf4efdd720089) includes this line that you can modify:
```python
system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME, rigidWater=True, constraints=app.HBonds)
```
The `constraints=app.HBonds` argument constrains only bonds involving hydrogen in the small molecule, which is common practice (and enables use of larger timesteps). You might also want to use hydrogen mass repartitioning if you want to use large timesteps, such as the 4 fs timestep in the example, by adding `hydrogenMass=3*unit.amu`.

You can change the constraint behavior for `createSystem` as described in [the API docs](http://docs.openmm.org/latest/api-python/generated/openmm.app.forcefield.ForceField.html#openmm.app.forcefield.ForceField.createSystem). If you use `constraints=None`, you will want to reduce the timestep to 1 or 2 fs, since 4 fs will likely be unstable.

**Comment by mattwthompson** [comment]
@SchroedingersLion have you been able to get this working? There doesn't seem to be a bug here - just wading through the muddy waters of all of these files and tools - so I'm inclined to close this if your pipelines is buzzing along now

**Comment by SchroedingersLion** [comment]
@mattwthompson 
Yes, this thread can be closed. Everything works. Thank you!
