### ISSUE TITLE
Harmonize prefixes for AMBER protein force field additions

### ISSUE THREAD

**Issue by jchodera** [openmm/openmmforcefields#99]
Currently, we have an issue where some converted AMBER protein force field files contain the prefixe `protein-` while others do not, causing seemingly straightforward operations like bringing in the phosphoaminoacid templates:
```python
from simtk.openmm.app import ForceField
ff = ForceField('amber/protein.ff14SB.xml', 'amber/phosaa10.xml')
```
to fail:
```
Traceback (most recent call last):
 File “<stdin>“, line 1, in <module>
 File “/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py”, line 185, in __init__
  self.loadFile(files)
 File “/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py”, line 278, in loadFile
  template.atoms.append(ForceField._TemplateAtomData(atomName, typeName, self._atomTypes[typeName].element, params))
KeyError: ‘N’
```
We therefore need to decide whether we want to harmonize these by prefixing _all_ protein atom types with `protein-` so these will be compatible.

We can support this by adding [a line to the YAML](https://github.com/openmm/openmmforcefields/blob/master/amber/biopolymer.yaml#L9):
```
  Prefix: protein
```
for each file we want to convert and prepend prefixes for atom types.

Questions:
* Which files should we do this with?
* Should we also do this with all files in `oldff/`?
* How should we augment the tests to catch these incompatibilities

cc: @rafwiewiora @hannahbrucemacdonald @peastman 

We should likely include the fixed parameters and information on how to use the small molecule parameters in an upcoming OpenMM release.

**Comment by hannahbrucemacdonald** [comment]
Is there something inherently different between those that are prefixed, and those that aren't?

**Comment by jchodera** [comment]
From what I recall, @peastman was concerned about atom type and class name collisions between different ffxml files packaged with OpenMM. I believe that's why we added prefixes for those ffxml files that were to be packaged with OpenMM, but we likely need to do this for all recipes if we are going to do this for any.

**Comment by jchodera** [comment]
@peastman: Some of the AMBER force field files we are converting contain only protein, only lipid, or only nucleic acid parameters, but others (such as `leaprc.PM3`) contain a mixture of multiple kinds. 

I seem to recall we originally introduced these prefixes (`protein-`, `DNA-`, `RNA-`) to avoid clashes between TIP3P water type names (which are prefixed with `tip3p`) and biopolymer atom type names, but it would seem sufficient to only retain the prefixes for water modesl.

How should we proceed?
1. Only retain prefixes for water models so that everything is compatible
2. Keep the `protein-`, `DNA-`, `RNA-`, etc prefixes for existing files and add them to other files, leaving them absent from files that contain mixtures (hoping the user never needs to use these together with other files)
3. Something else?

I am currently favoring Option 1, but wanted to check first in case this breaks something.

**Comment by peastman** [comment]
See the discussion beginning at https://github.com/openmm/openmm/issues/1611#issuecomment-340058384.  It had to do with the history of how the Amber force fields were developed, which led to a lot of duplicated definitions in different files.

**Comment by rafwiewiora** [comment]
As Peter's pointed out, this is not due to waters -- there were two 'formats' of AMBER leaprc's -- the old mixed proteins and nucleic acids and had shared atom types // the new split protein, DNA, and RNA and in each of those three the shared atom types now had to appear separately -- rather than trying to work out which types to delete in which file, to avoid the OpenMM duplicate atom type error, we decided to add the prefixes so that the atom types are no longer shared. 

**Note phosaa10.xml should be the only file this issue affects.**

I thought we already had a solution -- make another copy of phosaa10, called `protein.phosaa10.xml` which will use the `protein-` prefix and be usable with the `protein.XXX.xml` files, while `phosaa10.xml` will be usable with the mixed files from `oldff/`.

**Comment by hannahbrucemacdonald** [comment]
I can make the fix as Rafal described!

**Comment by hannahbrucemacdonald** [comment]
Ok - I've added the `protein-` prefix, to the `protein.phospha10.xml` file, however it complains because there is no entry for "P" in either `protein.phospha10.xml` or `protein.ff14SB.xml`. If I manually add the atom type to the file:

`<Type element="P" name="protein-P" class="P" mass="30.97"/>`


Then I still get an error when running:

`INFO:openmmforcefields.generators.template_generators:Requested to generate parameters for residue <Residue 159 (TYR) of chain 0>
WARNING:openmmforcefields.generators.template_generators:Did not recognize residue TYR; did you forget to call .add_molecules() to add it?
Traceback (most recent call last):
  File "/home/brucemah/software/perses/perses/app/setup_relative_calculation.py", line 590, in <module>
    setup_dict = run_setup(setup_options)
  File "/home/brucemah/software/perses/perses/app/setup_relative_calculation.py", line 337, in run_setup
    small_molecule_forcefield=setup_options['small_molecule_forcefield'], small_molecule_parameters_cache=setup_options['small_molecule_parameters_cache'])
  File "/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/perses-0.4.0-py3.6.egg/perses/app/relative_setup.py", line 241, in __init__
    self._complex_topology_old, self._complex_positions_old)
  File "/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/perses-0.4.0-py3.6.egg/perses/app/relative_setup.py", line 585, in _solvate_system
    modeller.addSolvent(self._system_generator.forcefield, model=model, padding=self._padding, ionicStrength=0.15*unit.molar)
  File "/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/simtk/openmm/app/modeller.py", line 481, in addSolvent
    system = forcefield.createSystem(self.topology)
  File "/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1174, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 160 (TYR).  The set of atoms matches TYR, but the bonds are different.`



Residue 159 is Tyrosine, and residue 160 is the TPO which is the problem... (protein attached) 
[CDK2_protein.zip](https://github.com/openmm/openmmforcefields/files/4172651/CDK2_protein.zip)

**Comment by hannahbrucemacdonald** [comment]
I'm guessing there are still some parameters missing in the `protein.phospha10.xml` file, that were in `ff14SB.xml`, but not `protein.ff14SB.xml`.

I don't know if this is an issue because phosaa10 is parameterised for `ff10`?


'phospha' == 'phosaa'

**Comment by jchodera** [comment]
OK, this last problem is very confusing. Here's why:

`protein.ff14SB.xml` is a conversion of `leaprc.protein.ff14SB`, which contains
```
#
#       Load the main parameter set.
#
parm10 = loadamberparams parm10.dat
frcmod14SB = loadamberparams frcmod.ff14SB
#
#       Load main chain and terminating amino acid libraries
#
loadOff amino12.lib
loadOff aminoct12.lib
loadOff aminont12.lib
```
This should direct it to load `parm10.dat`, which defines the `P` atom type, along with many others:
```
PARM99 + frcmod.ff99SB + frcmod.parmbsc0 + OL3 for RNA
C  12.01         0.616  !            sp2 C carbonyl group 
CA 12.01         0.360               sp2 C pure aromatic (benzene)
CB 12.01         0.360               sp2 aromatic C, 5&6 membered ring junction
CC 12.01         0.360               sp2 aromatic C, 5 memb. ring HIS
CD 12.01         0.360               sp2 C atom in the middle of: C=CD-CD=C
CI 12.01                             parmbsc0
CK 12.01         0.360               sp2 C 5 memb.ring in purines (dA,dG)
CP 12.01         0.360               sp2 C 5 memb.ring in purines (G)
CM 12.01         0.360               sp2 C  pyrimidines in pos. 5 & 6 (dT,dC)
CS 12.01         0.360               sp2 C  pyrimidines in pos. 5 & 6 (U)
CN 12.01         0.360               sp2 C aromatic 5&6 memb.ring junct.(TRP)
CQ 12.01         0.360               sp2 C in 5 mem.ring of purines between 2 N
CR 12.01         0.360               sp2 arom as CQ but in HIS
CT 12.01         0.878               sp3 aliphatic C
CV 12.01         0.360               sp2 arom. 5 memb.ring w/1 N and 1 H (HIS)
CW 12.01         0.360               sp2 arom. 5 memb.ring w/1 N-H and 1 H (HIS)
C* 12.01         0.360               sp2 arom. 5 memb.ring w/1 subst. (TRP)
CX 12.01         0.360               protein C-alpha (new to ff10)
CY 12.01         0.360               nitrile C (Howard et al.JCC,16,243,1995)
CZ 12.01         0.360               sp C (Howard et al.JCC,16,243,1995)
C5 12.01         0.360               sp2 C 5 memb.ring in purines (A)
C4 12.01         0.360               sp2 C  pyrimidines in pos. 5 & 6 (C)
C0 40.08                             calcium
H  1.008         0.161               H bonded to nitrogen atoms
HC 1.008         0.135               H aliph. bond. to C without electrwd.group
H1 1.008         0.135               H aliph. bond. to C with 1 electrwd. group
H2 1.008         0.135               H aliph. bond. to C with 2 electrwd.groups
H3 1.008         0.135               H aliph. bond. to C with 3 eletrwd.groups
HA 1.008         0.167               H arom. bond. to C without elctrwd. groups
H4 1.008         0.167               H arom. bond. to C with 1 electrwd. group
H5 1.008         0.167               H arom.at C with 2 elctrwd. gr,+HCOO group
HO 1.008         0.135               hydroxyl group
HS 1.008         0.135               hydrogen bonded to sulphur (pol?)
HW 1.008         0.000               H in TIP3P water
HP 1.008         0.135               H bonded to C next to positively charged gr
HZ 1.008         0.161               H bond sp C (Howard et al.JCC,16,243,1995)
F  19.00         0.320               fluorine (not fluoride!)
Cl 35.45         1.910               chlorine  (Applequist) (not chloride!)
Br 79.90         2.880               bromine  (Applequist) (not bromide!)
I  126.9         4.690               iodine   (Applequist) (not iodide!)
MG 24.305        0.120               magnesium
N  14.01         0.530               sp2 nitrogen in amide groups
NA 14.01         0.530               sp2 N in 5 memb.ring w/H atom (HIS)
NB 14.01         0.530               sp2 N in 5 memb.ring w/LP (HIS,ADE,GUA)
NC 14.01         0.530               sp2 N in 6 memb.ring w/LP (ADE,GUA)
N2 14.01         0.530               sp2 N in amino groups
N3 14.01         0.530               sp3 N for charged amino groups (Lys, etc)
NT 14.01         0.530               sp3 N for amino groups amino groups 
N* 14.01         0.530               sp2 N 
NY 14.01         0.530               nitrile N (Howard et al.JCC,16,243,1995)
O  16.00         0.434               carbonyl group oxygen
O2 16.00         0.434               carboxyl and phosphate group oxygen
OW 16.00         0.000               oxygen in TIP3P water
OH 16.00         0.465               oxygen in hydroxyl group
OS 16.00         0.465               ether and ester oxygen
OP 16.00         0.465               2- phosphate oxygen
P  30.97         1.538               phosphate,pol:JACS,112,8543,90,K.J.Miller
S  32.06         2.900               S in disulfide linkage,pol:JPC,102,2399,98
SH 32.06         2.900               S in cystine
CU 63.55                             copper
FE 55.00                             iron
```
However, the `protein.ff14SB.xml` only contains a small subset of these types:
```XML
  <AtomTypes>
    <Type element="C" name="protein-C" class="C" mass="12.01"/>
    <Type element="C" name="protein-CA" class="CA" mass="12.01"/>
    <Type element="C" name="protein-CB" class="CB" mass="12.01"/>
    <Type element="C" name="protein-CC" class="CC" mass="12.01"/>
    <Type element="C" name="protein-CN" class="CN" mass="12.01"/>
    <Type element="C" name="protein-CR" class="CR" mass="12.01"/>
    <Type element="C" name="protein-CT" class="CT" mass="12.01"/>
    <Type element="C" name="protein-CV" class="CV" mass="12.01"/>
    <Type element="C" name="protein-CW" class="CW" mass="12.01"/>
    <Type element="C" name="protein-C*" class="C*" mass="12.01"/>
    <Type element="C" name="protein-CX" class="CX" mass="12.01"/>
    <Type element="H" name="protein-H" class="H" mass="1.008"/>
    <Type element="H" name="protein-HC" class="HC" mass="1.008"/>
    <Type element="H" name="protein-H1" class="H1" mass="1.008"/>
    <Type element="H" name="protein-HA" class="HA" mass="1.008"/>
    <Type element="H" name="protein-H4" class="H4" mass="1.008"/>
    <Type element="H" name="protein-H5" class="H5" mass="1.008"/>
    <Type element="H" name="protein-HO" class="HO" mass="1.008"/>
    <Type element="H" name="protein-HS" class="HS" mass="1.008"/>
    <Type element="H" name="protein-HP" class="HP" mass="1.008"/>
    <Type element="N" name="protein-N" class="N" mass="14.01"/>
    <Type element="N" name="protein-NA" class="NA" mass="14.01"/>
    <Type element="N" name="protein-NB" class="NB" mass="14.01"/>
    <Type element="N" name="protein-N2" class="N2" mass="14.01"/>
    <Type element="N" name="protein-N3" class="N3" mass="14.01"/>
    <Type element="O" name="protein-O" class="O" mass="16.0"/>
    <Type element="O" name="protein-O2" class="O2" mass="16.0"/>
    <Type element="O" name="protein-OH" class="OH" mass="16.0"/>
    <Type element="S" name="protein-S" class="S" mass="32.06"/>
    <Type element="S" name="protein-SH" class="SH" mass="32.06"/>
    <Type element="C" name="protein-CO" class="CO" mass="12.01"/>
    <Type element="C" name="protein-2C" class="2C" mass="12.01"/>
    <Type element="C" name="protein-3C" class="3C" mass="12.01"/>
    <Type element="C" name="protein-C8" class="C8" mass="12.01"/>
  </AtomTypes>
```
It looks like it may be dropping types that are not used in the protein residue definitions included in this file, because the [`write_unused`](https://github.com/openmm/openmmforcefields/blob/master/amber/convert_amber.py#L161-L162) flag is set to `False` when having ParmEd write the parameters.

However, I'm not entirely sure if we'll suddenly run into lots of parameter collisions if we set it to `True` in the `biopolymers.yaml` file. Let me try it and see in a PR.

@hannahbrucemacdonald : I'll pull your bace test into my PR.

**Comment by jchodera** [comment]
OK, we _can't_ use `write_unused=True` because this results in an exception when OpenMM's `ForceField` encounters multiple definitions of the same type (even if they are identical):
```
>>> ff = ForceField('protein.ff14SB.xml', 'phosaa10.xml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/envs/openmmforcefields/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 185, in __init__
    self.loadFile(files)
  File "/Users/choderaj/miniconda/envs/openmmforcefields/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 256, in loadFile
    self.registerAtomType(type.attrib)
  File "/Users/choderaj/miniconda/envs/openmmforcefields/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 390, in registerAtomType
    raise ValueError('Found multiple definitions for atom type: '+name)
ValueError: Found multiple definitions for atom type: OP
```
(Here, I've removed the `protein-` prefix from both files.)

It turns out that `phosaa10.xml` doesn't end up containing the `P` type because it does not source from `parm10.dat` first, since you're supposed to load it after sourcing `learpc.ff14SB`.

**Comment by jchodera** [comment]
@peastman: The simple solution to this otherwise nightmarish scenario is to simply allow `ForceField` to permit atom types to be redefined if the new definition _is identical to_ the previous definition. Would you permit something like this?

Another alternative---that would require much more engineering and break all of the AMBER philosophy of mix-and-match---is to bundle EVERYTHING that could be conceivably used together into prebundled `xml` files, but this would start to get combinatorially large.

**Comment by peastman** [comment]
I'd be nervous about making that the default behavior.  If two files define types with the same name, there's a good chance it's an unintentional collision.  But we could add an optional attribute in the XML file to say, "These types may have already been defined in another file and that's ok."

Another option would be to provide a name for the "atom type set", and it's ok to have repeats as long as both files specified the same name.

**Comment by jchodera** [comment]
> Another option would be to provide a name for the "atom type set", and it's ok to have repeats as long as both files specified the same name.

I like this idea a lot. What if this behavior also allowed the atom type sets to be kept disjoint by internally forming prefixes? That is, instead of worrying about clashes in atom names by appending prefixes manually, I could just lump all the AMBER parameters of one generation into the "amber-protein" atom type set, and it's OK if the typename `O` was used in both that and a "third-party-lipid" atom type set? Internally, they'd end up with `amber-protein-O`, and `third-party-lipid-O`?

**Comment by peastman** [comment]
That seems possible.  Let's think this through a bit.  What you're proposing is that the type set name should serve two functions:

1. Distinguishing unrelated atom types that happen to have the same name.
2. Marking atom types that may appear in multiple files as the same.

The logic would work something like this:

- If the `<ForceField>` tag includes the `atomTypePrefix` attribute, the prefix is added to every atom type name that appears anywhere in the file, either to define it or to use it in a force definition.
- If two files define atom types with the same name,
  - If they have different prefixes, there's no collision and everything is fine.
  - If they have the same prefix, it accepts the repeat definition and doesn't report an error.
  - If they don't specify a prefix, it views this as a collision and reports an error.

Are there any situations where this would cause problems, like if you want to use atom types from different sets in the same file?

The alternative is that we keep these functions separate.  There's a flag to say, "It's ok if this type has already been defined," and that's independent of what prefixes are used.

**Comment by jchodera** [comment]
> Are there any situations where this would cause problems, like if you want to use atom types from different sets in the same file?

I think we'd have to be careful to use the prefix to define a whole domain of parameters that could conceivably covalently bonded. For example, amino acid and post-translational modification definitions would need to be in the same prefix domain, as would any small molecule force field intended to be compatible with them if it could ever be covalently bonded. But in nearly all the cases I think think of, this allows a lot more freedom to mix and match independently derived parameter domains---such as various generations of AMBER parameters intended to be compatible.

One more caution:

> If they have the same prefix, it accepts the repeat definition and doesn't report an error.

Presumably it will only accept the repeat type definition that is identical, and not one that introduces a modified definition (since it would depend on file ordering at that point).

> The alternative is that we keep these functions separate. There's a flag to say, "It's ok if this type has already been defined," and that's independent of what prefixes are used.

The optional prefixed domains sound much more useful!

**Comment by peastman** [comment]
> Presumably it will only accept the repeat type definition that is identical, and not one that introduces a modified definition (since it would depend on file ordering at that point).

Correct, but there isn't really much in a type definition.  Just the element and mass.  Everything else comes from how it gets used in templates and force definitions.  It would be very hard to check all of that to verify they're really being used in a consistent way.

**Comment by jchodera** [comment]
I was just suggesting the element and mass would be identical, but maybe it's not even worth checking the mass if it may be useful to redefine the mass to experiment with HMR-like method sin the future.

**Comment by rafwiewiora** [comment]
So, you’re doing this because you want to use `phosaa10` with `ff14SB` — but this is the header of `leaprc.phosaa10` (from AmberTools19 I just downloaded just to be sure):

```
#
# ----- leaprc for loading phosphorylated amino acid residues
#
# This file contains charges and force field parameters for phosphorylated 
# amino acids under the ff99SB protein force field (and related ff94/96/99 
# force fields). We recommend that you do *NOT* use these parameters with the 
# ff14SB protein force field as the requisite atom types are not present and 
# the dihedral potentials will be mismatched. (The Simmerling group hopes to 
# release ff14SB-compatible parameters for phosphorylated amino acids later 
# in 2016.) Also note that the bond, angle, and dihedral terms are mostly 
# generic and taken from analogy with existing terms in parm99.dat. 
```

Not clear what they mean by ‘requisite atom types are not present’ because it works fine if you use `ff14SB.xml` (without protein prefix) — are some atom types of the same names but with different params in the new ff?

If it’s indeed right that you can’t combine the `ff14SB` with `phosaa10` then the way we have it now is actually good — using it with protein.ff14SB.xml is prevented by the error so user of OpenMM (without openmmforcefields) has to use the old-conversion ff99SBildn.xml

**Comment by jchodera** [comment]
@rafwiewiora: You're right that combining `ff14SB.xml` and `phosaa10.xml` actually may work (!!!) because the nucleic acids are fortuitously included in the `ff14SB.xml` file, meaning there is a `P` type defined. But it seems we're going to run into trouble pretty rapidly if we don't find a way to deal with the AMBER habit of randomly sorting residues and types into different files.
